# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - main
      - automated_tests
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt install libopengl0
        sudo apt install pybind11-dev
        python -m pip install --upgrade pip
        pip install coverage pybind11==2.9.1
        pip install -r requirements.txt

    - name: Install Sofa dependencies
      run: |
        export SOFA_ROOT=./sofa_install
        export PYTHONPATH=./sofa_install/plugins/SofaPython3/lib/python3/site-packages:$PYTHONPATH
    
    - name: Test with unittest
      run: |
        python3 test_main.py

    - name: Analyse code coverage of tests with coverage
      run: |
        coverage run test_main.py
        coverage report -m