# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - main
      - automated_tests
      - windows
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup SOFA and environment
      uses: orthographiepro/sofa-setup-action@f498e4b2163d3fff4435f1bf4a6d4638b416b214
      with:
        sofa_root: ${{ github.workspace }}/sofa
        sofa_version: 'v24.06'
        python_version: '3.10'
        workspace_auto_setup: 'false'


    - uses: actions/checkout@v4

    - name: Install our dependencies
      run: |
        pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    
    - name: Test with coverage and analyze coverage
      run: |
        set PYTHONPATH="$PYTHONPATH"
        set SOFA_ROOT="$SOFA_ROOT"
        set PYTHON_ROOT="$PYTHON_ROOT"
        set PATH="%PATH%;$PYTHON_ROOT;$PYTHON_ROOT\DLLs;$PYTHON_ROOT\Lib;$SOFA_ROOT\bin;"
        coverage run test_main.py
        coverage report -m