# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - main
      - automated_tests
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Qt
      uses: jurplel/install-qt-action@v4

    - name: Install dependencies (not libegl1 libopengl0 libxcb-xinerama0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0)
      run: |
        sudo apt install pybind11-dev libxcb-cursor0
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip install coverage pybind11==2.9.1
        python3.10 -m pip install -r requirements.txt
    
    - name: Test with coverage and analyze coverage
      run: |
        export SOFA_ROOT=$PWD/sofa_install
        export PYTHONPATH=$PWD/sofa_install/plugins/SofaPython3/lib/python3/site-packages:$PYTHONPATH
        export QT_QPA_PLATFORM=xcb
        export QT_DEBUG_PLUGINS=1
        echo $SOFA_ROOT
        echo $PYTHONPATH
        coverage run test_main.py
        coverage report -m